version: '3.7'
services:
  app:
    container_name: app
    image: demo-auction
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/auction-handler
    environment:
      bidOperationType: SEQUENTIAL
      bidders: http://172.18.0.4:8081,http://172.18.0.5:8082,http://172.18.0.6:8083
    ports:
      - "8080:8080"
    networks:
      auction_containers:
        ipv4_address: 172.18.0.3
  yieldlab1:
    container_name: yieldlab1
    image: yieldlab/recruiting-test-bidder
    ports:
      - "8081:8081"
    environment:
      biddingTrigger: a
      initial: 150
      server.port: 8081
    networks:
      auction_containers:
        ipv4_address: 172.18.0.4
  yieldlab2:
    container_name: yieldlab2
    image: yieldlab/recruiting-test-bidder
    ports:
      - "8082:8082"
    environment:
      biddingTrigger: b
      initial: 250
      server.port: 8082
    networks:
      auction_containers:
        ipv4_address: 172.18.0.5
  yieldlab3:
    container_name: yieldlab3
    image: yieldlab/recruiting-test-bidder
    ports:
      - "8083:8083"
    environment:
      biddingTrigger: c
      initial: 500
      server.port: 8083
    networks:
      auction_containers:
        ipv4_address: 172.18.0.6
networks:
  auction_containers:
    external:
      name: auction